export const colleges: string[] = [
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Santa Barbara",
  "University of California, Santa Cruz",
  "University of California, Riverside",
  "University of California, Merced",
  "California State University, Long Beach",
  "California State University, Fullerton",
  "San Diego State University",
  "San Francisco State University",
  "San Jose State University",
  "California Polytechnic State University",
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Brown University",
  "Dartmouth College",
  "Cornell University",
  "Stanford University",
  "Massachusetts Institute of Technology",
  "University of Chicago",
  "Northwestern University",
  "Duke University",
  "Johns Hopkins University",
  "Carnegie Mellon University",
  "New York University",
  "Georgetown University",
  "Vanderbilt University",
  "University of Michigan",
  "University of Wisconsin-Madison",
  "University of Illinois at Urbana-Champaign",
  "University of Texas at Austin",
  "University of North Carolina at Chapel Hill",
  "University of Virginia",
  "University of Florida",
  "University of Georgia",
  "University of Washington",
  "University of Oregon",
  "Arizona State University",
  "University of Arizona",
  "University of Colorado Boulder",
  "University of Utah",
  "University of Nevada, Las Vegas",
  "Santa Monica College",
  "De Anza College",
  "Pasadena City College",
  "Orange Coast College",
  "Miami Dade College",
  "Lone Star College",
  "Houston Community College",
  "Broward College",
  "Austin Community College",
  "Valencia College",
  "University of Southern California",
  "California Institute of Technology",
  "Pomona College",
  "Claremont McKenna College",
  "Harvey Mudd College",
  "Scripps College",
  "Pitzer College",
  "Occidental College",
  "Loyola Marymount University",
  "Pepperdine University",
  "University of British Columbia",
  "McGill University",
  "University of Toronto",
  "University of Waterloo",
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "London School of Economics",
  "University College London",
  "King's College London",
  "Case Western Reserve University",
  "The Ohio State University",
  "University of Miami",
  "University of Texas at Dallas",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at San Antonio",
  "University of Texas at Dallas",
];

export const searchColleges = (query: string): string[] => {
  if (!query.trim()) return colleges;
  
  const lowercaseQuery = query.toLowerCase();
  return colleges.filter(college => 
    college.toLowerCase().includes(lowercaseQuery)
  );
};
