export const academicFields: string[] = [
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Robotics",
  "Cybersecurity",
  "Blockchain",
  "Computer Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Environmental Engineering",
  "Geological Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Statistics",
  "Data Science",
  "Information Technology",
  "Cybersecurity",
  "Geology",
  "Astronomy",
  "Neuroscience",
  "Business Administration",
  "Finance",
  "Accounting",
  "Marketing",
  "Economics",
  "International Business",
  "Management",
  "Entrepreneurship",
  "Supply Chain Management",
  "Human Resources",
  "Business Management",
  "Pre-Medicine",
  "Nursing",
  "Psychology",
  "Public Health",
  "Health Administration",
  "Pharmacy",
  "Physical Therapy",
  "Occupational Therapy",
  "Nutrition",
  "Kinesiology",
  "Political Science",
  "Sociology",
  "Anthropology",
  "History",
  "Geography",
  "International Relations",
  "Social Work",
  "Criminal Justice",
  "Communication",
  "Journalism",
  "English",
  "Literature",
  "Philosophy",
  "Art",
  "Music",
  "Theater",
  "Film Studies",
  "Creative Writing",
  "Linguistics",
  "Religious Studies",
  "Education",
  "Early Childhood Education",
  "Elementary Education",
  "Secondary Education",
  "Special Education",
  "Architecture",
  "Graphic Design",
  "Interior Design",
  "Urban Planning",
  "Landscape Architecture",
  "Agriculture",
  "Environmental Studies",
  "Forestry",
  "Marine Biology",
  "Wildlife Biology",
  "Sports Management",
  "Hospitality Management",
  "Tourism",
  "Real Estate",
  "Library Science",
  "Museum Studies",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Chinese",
  "Japanese",
  "Arabic",
  "Russian",
  "Leadership",
  "Sustainability",
  "Gender Studies",
  "African American Studies",
  "Latin American Studies",
  "Asian Studies",
  "International Studies",
  "Pre-Law",
  "Pre-Medicine",
];

export const searchAcademicFields = (query: string): string[] => {
  if (!query.trim()) return academicFields;
  
  const lowercaseQuery = query.toLowerCase();
  return academicFields.filter(item => 
    item.toLowerCase().includes(lowercaseQuery)
  );
};