export const SUBJECTS = [
  'Math',
  'Science',
  'History',
  'English',
  'Biology',
  'Chemistry',
  'Physics',
  'Economics',
  'Political Science',
  'Sociology',
  'Psychology',
  'Philosophy',
  'Art',
  'Music',
  'Dance',
  'Theater',
  'Film',
  'Literature',
  'Languages',
  'Computer Science',
  'Engineering',
  'Business',
  'Law',
  'Medicine',
  'Nursing',
  'Pharmacy',
  'Veterinary Science',
  'Agriculture',
  'Architecture',
  'AI',
  'Other'
]